# Generated by Django 2.2.4 on 2020-03-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='effort_in_hours',
            field=models.TimeField(null=True),
        ),
    ]
